<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-26 at 20:25:33.
 */
class RouterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Router
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Router;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Router::route
     * @todo   Implement testRoute().
     */
    public function testRoute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
